apiVersion: v2
name: opensearch-operator
description: A Helm chart for Kubernetes OpenSearch Operator

home: https://github.com/Opster/opensearch-k8s-operator
icon: https://opster.com/wp-content/uploads/2022/04/Opster_Logo_Rectangle_Dark.svg
maintainers:
  - email: idan@opster.com
    name: Idan levi
  - email: ori.g@opster.com
    name: Ori Goldstein
sources:
  - https://github.com/Opster/opensearch-k8s-operator
version: "1.1"
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"


