nodeSelector: {}
manager:
  tolerations: []
  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 2
      memory: 1Gi
  image:
    repository: public.ecr.aws/opsterio/opensearch-operator
    tag: latest
